package exporter

import (
	"encoding/json"
	"errors"
	"fmt"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"sessionport/internal/domain"
	"sessionport/internal/platform/fsx"
)

type Options struct {
	FS     fsx.FS
	Bundle domain.SessionBundle
	Report domain.CompatibilityReport
	OutDir string
}

func Export(opts Options) (domain.ExportManifest, error) {
	if opts.FS == nil {
		return domain.ExportManifest{}, errors.New("fs is required")
	}
	if opts.OutDir == "" {
		return domain.ExportManifest{}, errors.New("out_dir is required")
	}
	if opts.Bundle.AssetKind == "" {
		opts.Bundle.AssetKind = domain.AssetKindSession
	}
	if err := opts.Bundle.Validate(); err != nil {
		return domain.ExportManifest{}, err
	}
	if !opts.Report.TargetTool.IsKnown() {
		return domain.ExportManifest{}, fmt.Errorf("unsupported target tool %q", opts.Report.TargetTool)
	}

	files := filesForTarget(opts.Bundle, opts.Report)
	fileNames := make([]string, 0, len(files)+1)
	for name := range files {
		fileNames = append(fileNames, name)
	}
	sort.Strings(fileNames)
	expectedArtifacts := append([]string{}, opts.Report.GeneratedArtifacts...)
	sort.Strings(expectedArtifacts)
	if !slices.Equal(fileNames, expectedArtifacts) {
		return domain.ExportManifest{}, fmt.Errorf("generated artifact mismatch: report=%v exporter=%v", expectedArtifacts, fileNames)
	}

	if err := opts.FS.MkdirAll(opts.OutDir, 0o755); err != nil {
		return domain.ExportManifest{}, err
	}
	for _, name := range fileNames {
		fullPath := filepath.Join(opts.OutDir, name)
		if err := opts.FS.WriteFile(fullPath, []byte(files[name]), 0o644); err != nil {
			return domain.ExportManifest{}, err
		}
	}

	manifest := domain.ExportManifest{
		AssetKind:         opts.Bundle.AssetKind,
		BundleID:          opts.Bundle.BundleID,
		SourceTool:        opts.Bundle.SourceTool,
		SourceSessionID:   opts.Bundle.SourceSessionID,
		TargetTool:        opts.Report.TargetTool,
		OutputDir:         opts.OutDir,
		Files:             append(append([]string{}, fileNames...), "manifest.json"),
		PartialFields:     append([]string{}, opts.Report.PartialFields...),
		UnsupportedFields: append([]string{}, opts.Report.UnsupportedFields...),
		RedactedFields:    append([]string{}, opts.Report.RedactedFields...),
		Warnings:          append([]string{}, opts.Report.Warnings...),
	}

	manifestData, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return domain.ExportManifest{}, err
	}
	if err := opts.FS.WriteFile(filepath.Join(opts.OutDir, "manifest.json"), append(manifestData, '\n'), 0o644); err != nil {
		return domain.ExportManifest{}, err
	}

	return manifest, nil
}

func filesForTarget(bundle domain.SessionBundle, report domain.CompatibilityReport) map[string]string {
	switch report.TargetTool {
	case domain.ToolCodex:
		return map[string]string{
			"AGENTS.sessionport.md": renderCodexSupplement(bundle, report),
			"CONFIG_HINTS.md":       renderConfigHints(bundle, "codex"),
			"STARTER_PROMPT.md":     renderStarterPrompt(bundle, report, "Codex"),
		}
	case domain.ToolGemini:
		return map[string]string{
			"GEMINI.sessionport.md": renderGeminiSupplement(bundle, report),
			"SETTINGS_PATCH.json":   renderSettingsPatch(bundle),
			"STARTER_PROMPT.md":     renderStarterPrompt(bundle, report, "Gemini"),
		}
	case domain.ToolClaude:
		return map[string]string{
			"CLAUDE.sessionport.md": renderClaudeSupplement(bundle, report),
			"MEMORY_NOTE.md":        renderMemoryNote(bundle, report),
			"STARTER_PROMPT.md":     renderStarterPrompt(bundle, report, "Claude"),
		}
	default:
		return map[string]string{}
	}
}

func renderCodexSupplement(bundle domain.SessionBundle, report domain.CompatibilityReport) string {
	return renderInstructionSupplement("Codex", "AGENTS.md supplement generated by sessionport.", bundle, report)
}

func renderGeminiSupplement(bundle domain.SessionBundle, report domain.CompatibilityReport) string {
	return renderInstructionSupplement("Gemini", "GEMINI.md supplement generated by sessionport.", bundle, report)
}

func renderClaudeSupplement(bundle domain.SessionBundle, report domain.CompatibilityReport) string {
	return renderInstructionSupplement("Claude", "CLAUDE.md supplement generated by sessionport.", bundle, report)
}

func renderInstructionSupplement(target string, intro string, bundle domain.SessionBundle, report domain.CompatibilityReport) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# sessionport %s supplement\n\n", target)
	fmt.Fprintf(&b, "%s\n\n", intro)
	fmt.Fprintf(&b, "- Source tool: %s\n", bundle.SourceTool)
	if bundle.SourceSessionID != "" {
		fmt.Fprintf(&b, "- Source session: %s\n", bundle.SourceSessionID)
	}
	fmt.Fprintf(&b, "- Project root: %s\n\n", bundle.ProjectRoot)

	if bundle.TaskTitle != "" {
		fmt.Fprintf(&b, "## Task title\n\n%s\n\n", bundle.TaskTitle)
	}
	if bundle.CurrentGoal != "" {
		fmt.Fprintf(&b, "## Current goal\n\n%s\n\n", bundle.CurrentGoal)
	}
	if bundle.Summary != "" {
		fmt.Fprintf(&b, "## Summary\n\n%s\n\n", bundle.Summary)
	}

	if len(bundle.InstructionArtifacts) > 0 {
		fmt.Fprintf(&b, "## Imported instructions\n\n")
		for _, artifact := range bundle.InstructionArtifacts {
			fmt.Fprintf(&b, "### %s (%s)\n\n", artifact.Path, artifact.Scope)
			if artifact.Content != "" {
				fmt.Fprintln(&b, "```md")
				b.WriteString(strings.TrimSpace(artifact.Content))
				fmt.Fprintln(&b, "\n```")
				fmt.Fprintln(&b)
			}
		}
	}

	if len(bundle.Decisions) > 0 {
		fmt.Fprintf(&b, "## Decisions\n\n")
		for _, decision := range bundle.Decisions {
			fmt.Fprintf(&b, "- %s\n", decision.Summary)
		}
		fmt.Fprintln(&b)
	}
	if len(bundle.Failures) > 0 {
		fmt.Fprintf(&b, "## Failures\n\n")
		for _, failure := range bundle.Failures {
			fmt.Fprintf(&b, "- %s\n", failure.Summary)
		}
		fmt.Fprintln(&b)
	}
	if len(report.Warnings) > 0 {
		fmt.Fprintf(&b, "## Portability notes\n\n")
		for _, warning := range report.Warnings {
			fmt.Fprintf(&b, "- %s\n", warning)
		}
	}

	return b.String()
}

func renderConfigHints(bundle domain.SessionBundle, target string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s config hints\n\n", target)
	if len(bundle.SettingsSnapshot.Included) == 0 {
		fmt.Fprintln(&b, "No portable settings were captured.")
	} else {
		fmt.Fprintln(&b, "Portable settings captured from the source bundle:")
		keys := sortedKeys(bundle.SettingsSnapshot.Included)
		for _, key := range keys {
			fmt.Fprintf(&b, "- %s: %s\n", key, mustJSONString(bundle.SettingsSnapshot.Included[key]))
		}
	}
	if len(bundle.SettingsSnapshot.ExcludedKeys) > 0 {
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "Excluded sensitive or vendor-specific keys:")
		for _, key := range bundle.SettingsSnapshot.ExcludedKeys {
			fmt.Fprintf(&b, "- %s\n", key)
		}
	}
	return b.String()
}

func renderSettingsPatch(bundle domain.SessionBundle) string {
	if len(bundle.SettingsSnapshot.Included) == 0 {
		return "{}\n"
	}
	data, err := json.MarshalIndent(bundle.SettingsSnapshot.Included, "", "  ")
	if err != nil {
		return "{}\n"
	}
	return string(data) + "\n"
}

func renderMemoryNote(bundle domain.SessionBundle, report domain.CompatibilityReport) string {
	var b strings.Builder
	fmt.Fprintln(&b, "# sessionport memory note")
	fmt.Fprintln(&b)
	if bundle.Summary != "" {
		fmt.Fprintln(&b, "## Session summary")
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, bundle.Summary)
		fmt.Fprintln(&b)
	}
	if len(bundle.ResumeHints) > 0 {
		fmt.Fprintln(&b, "## Resume hints")
		fmt.Fprintln(&b)
		for _, hint := range bundle.ResumeHints {
			fmt.Fprintf(&b, "- %s\n", hint)
		}
		fmt.Fprintln(&b)
	}
	if len(report.Warnings) > 0 {
		fmt.Fprintln(&b, "## Portability warnings")
		fmt.Fprintln(&b)
		for _, warning := range report.Warnings {
			fmt.Fprintf(&b, "- %s\n", warning)
		}
	}
	return b.String()
}

func renderStarterPrompt(bundle domain.SessionBundle, report domain.CompatibilityReport, targetName string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s starter prompt\n\n", targetName)
	fmt.Fprintf(&b, "Continue the imported working state from `%s`.\n\n", bundle.SourceTool)
	if bundle.TaskTitle != "" {
		fmt.Fprintf(&b, "Task title: %s\n", bundle.TaskTitle)
	}
	if bundle.CurrentGoal != "" {
		fmt.Fprintf(&b, "Current goal: %s\n", bundle.CurrentGoal)
	}
	if bundle.ProjectRoot != "" {
		fmt.Fprintf(&b, "Project root: %s\n", bundle.ProjectRoot)
	}
	if bundle.Summary != "" {
		fmt.Fprintf(&b, "\nContext summary:\n%s\n", bundle.Summary)
	}
	if len(report.PartialFields) > 0 {
		fmt.Fprintf(&b, "\nPartial portability fields:\n")
		for _, field := range report.PartialFields {
			fmt.Fprintf(&b, "- %s\n", field)
		}
	}
	if len(report.Warnings) > 0 {
		fmt.Fprintf(&b, "\nWarnings:\n")
		for _, warning := range report.Warnings {
			fmt.Fprintf(&b, "- %s\n", warning)
		}
	}
	return b.String()
}

func sortedKeys(values map[string]any) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func mustJSONString(value any) string {
	data, err := json.Marshal(value)
	if err != nil {
		return `"<unrenderable>"`
	}
	return string(data)
}
