// Package pathpatch provides utilities for translating absolute paths across
// machines when migrating AI agent sessions. Each agent uses a different
// strategy to map a project's absolute path to a storage location; this
// package re-implements those strategies so work-bridge can produce correct
// target directory names and patch stale paths inside exported payloads.
package pathpatch

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"regexp"
	"strings"
)

// ClaudeProjectDirName converts an absolute project path to the directory name
// that Claude Code uses under ~/.claude/projects/. Claude replaces every
// non-alphanumeric, non-hyphen character with a hyphen and strips leading /
// slashes from the result.
//
// Example: /Users/alice/myproject → -Users-alice-myproject
func ClaudeProjectDirName(absolutePath string) string {
	if absolutePath == "" {
		return ""
	}
	var b strings.Builder
	for _, r := range absolutePath {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == '-':
			b.WriteRune(r)
		default:
			b.WriteByte('-')
		}
	}
	result := b.String()
	// Collapse consecutive hyphens that arise from path separators, keeping
	// the leading hyphen that replaces the leading slash.
	for strings.Contains(result, "--") {
		result = strings.ReplaceAll(result, "--", "-")
	}
	return result
}

// GeminiProjectHashLegacy returns the SHA-256 hex digest of absolutePath,
// which is the legacy project storage key used by Gemini CLI before it
// switched to slug-based identifiers. Some installations still use hashes.
//
// Example: /Users/alice/myproject → sha256hex("/Users/alice/myproject")
func GeminiProjectHashLegacy(absolutePath string) string {
	sum := sha256.Sum256([]byte(absolutePath))
	return hex.EncodeToString(sum[:])
}

// GeminiProjectSlug derives the slug that Gemini CLI would assign to a project
// at absolutePath given the existing mapping in projectsJSON. projectsJSON maps
// absolute project paths to their current slug. If absolutePath is already
// present, its existing slug is returned unchanged. Otherwise a new unique slug
// is generated by sanitising the directory name and appending an integer suffix
// when there is a collision.
func GeminiProjectSlug(absolutePath string, projectsJSON map[string]string) string {
	if slug, ok := projectsJSON[absolutePath]; ok {
		return slug
	}
	// derive a candidate from the last component of the path
	parts := strings.Split(strings.TrimRight(absolutePath, "/"), "/")
	candidate := sanitizeGeminiSlug(parts[len(parts)-1])
	if candidate == "" {
		candidate = "project"
	}
	// collect existing slugs to check for collisions
	existing := map[string]struct{}{}
	for _, slug := range projectsJSON {
		existing[slug] = struct{}{}
	}
	slug := candidate
	for i := 1; ; i++ {
		if _, taken := existing[slug]; !taken {
			break
		}
		slug = fmt.Sprintf("%s-%d", candidate, i)
	}
	return slug
}

func sanitizeGeminiSlug(name string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(name) {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == '-' || r == '_':
			b.WriteByte('-')
		}
	}
	return strings.Trim(b.String(), "-")
}

// PatchJSONBytes recursively replaces all occurrences of srcPath with dstPath
// inside every JSON string value in data. Object keys are not modified; only
// string values are scanned. The returned bytes are re-serialised from the
// patched structure, so whitespace may differ from the original.
func PatchJSONBytes(data []byte, srcPath, dstPath string) ([]byte, error) {
	if srcPath == "" || srcPath == dstPath {
		return data, nil
	}
	var root any
	if err := json.Unmarshal(data, &root); err != nil {
		return data, err
	}
	patched := patchAny(root, srcPath, dstPath)
	out, err := json.Marshal(patched)
	if err != nil {
		return data, err
	}
	return out, nil
}

// PatchJSONLBytes applies PatchJSONBytes to each newline-delimited JSON line in
// data. Lines that cannot be parsed as JSON are passed through unchanged.
func PatchJSONLBytes(data []byte, srcPath, dstPath string) []byte {
	if srcPath == "" || srcPath == dstPath {
		return data
	}
	scanner := bufio.NewScanner(bytes.NewReader(data))
	scanner.Buffer(make([]byte, 0, 1024*1024), 8*1024*1024)
	var out bytes.Buffer
	for scanner.Scan() {
		line := scanner.Bytes()
		trimmed := bytes.TrimSpace(line)
		if len(trimmed) == 0 {
			out.WriteByte('\n')
			continue
		}
		patched, err := PatchJSONBytes(trimmed, srcPath, dstPath)
		if err != nil {
			// not parseable JSON — pass through verbatim
			out.Write(line)
		} else {
			out.Write(patched)
		}
		out.WriteByte('\n')
	}
	return out.Bytes()
}

// PatchCodexSessionMetaCWD rewrites the cwd field in the very first JSON line
// of a Codex rollout JSONL file. Only the session_meta record (always the
// first line) is modified; all subsequent lines are re-emitted unchanged.
// Returns the patched content and whether any modification was actually made.
func PatchCodexSessionMetaCWD(data []byte, newCWD string) ([]byte, bool) {
	if newCWD == "" {
		return data, false
	}
	scanner := bufio.NewScanner(bytes.NewReader(data))
	scanner.Buffer(make([]byte, 0, 4*1024*1024), 16*1024*1024)

	var out bytes.Buffer
	first := true
	patched := false

	for scanner.Scan() {
		line := scanner.Bytes()
		if first {
			first = false
			modifiedLine, ok := patchCodexCWDLine(line, newCWD)
			if ok {
				out.Write(modifiedLine)
				patched = true
			} else {
				out.Write(line)
			}
		} else {
			out.Write(line)
		}
		out.WriteByte('\n')
	}
	return out.Bytes(), patched
}

// patchCodexCWDLine modifies a single JSON line that is expected to be a
// session_meta record, updating payload.cwd to newCWD.
func patchCodexCWDLine(line []byte, newCWD string) ([]byte, bool) {
	trimmed := bytes.TrimSpace(line)
	if len(trimmed) == 0 {
		return line, false
	}

	var record struct {
		Type    string          `json:"type"`
		Payload json.RawMessage `json:"payload"`
	}
	if err := json.Unmarshal(trimmed, &record); err != nil {
		return line, false
	}
	if record.Type != "session_meta" {
		return line, false
	}

	var payload map[string]any
	if err := json.Unmarshal(record.Payload, &payload); err != nil {
		return line, false
	}

	oldCWD, _ := payload["cwd"].(string)
	if oldCWD == newCWD {
		return line, false
	}
	payload["cwd"] = newCWD

	payloadBytes, err := json.Marshal(payload)
	if err != nil {
		return line, false
	}

	out := map[string]any{
		"type":    record.Type,
		"payload": json.RawMessage(payloadBytes),
	}
	// preserve any extra top-level fields
	var full map[string]any
	if err := json.Unmarshal(trimmed, &full); err == nil {
		for k, v := range full {
			if k != "type" && k != "payload" {
				out[k] = v
			}
		}
	}

	result, err := json.Marshal(out)
	if err != nil {
		return line, false
	}
	return result, true
}

// pathReplaceRegexp is used to match absolute-path-like strings within text.
var pathReplaceRegexp = regexp.MustCompile(`[^\s"']+`)

// ReplacePathsInText replaces every verbatim occurrence of srcPath with dstPath
// in an arbitrary text string (e.g. shell output, log lines). Unlike
// PatchJSONBytes this function operates on raw text without JSON awareness.
func ReplacePathsInText(text, srcPath, dstPath string) string {
	if srcPath == "" || srcPath == dstPath {
		return text
	}
	return strings.ReplaceAll(text, srcPath, dstPath)
}

// --- internal helpers ---

func patchAny(v any, src, dst string) any {
	switch typed := v.(type) {
	case string:
		if strings.Contains(typed, src) {
			return strings.ReplaceAll(typed, src, dst)
		}
		return typed
	case map[string]any:
		out := make(map[string]any, len(typed))
		for k, val := range typed {
			out[k] = patchAny(val, src, dst)
		}
		return out
	case []any:
		out := make([]any, len(typed))
		for i, item := range typed {
			out[i] = patchAny(item, src, dst)
		}
		return out
	default:
		return v
	}
}
